Repository inhwanK/gachicoding, pull requests merged in 2022-08, with the labels that each got.

#37 [FEATURE] 공지사항 도메인 및 공지사항 작성 기능
  src/main/java/org/deco/gachicoding/controller/RestNoticeController.java
  src/main/java/org/deco/gachicoding/domain/notice/Notice.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeSaveRequestDto.java
  src/main/java/org/deco/gachicoding/service/NoticeService.java
Labels: 개발

#39 [FEATURE] 공지사항 상세 보기 기능
  src/main/java/org/deco/gachicoding/controller/RestNoticeController.java
  src/main/java/org/deco/gachicoding/domain/notice/Notice.java
  src/main/java/org/deco/gachicoding/domain/notice/NoticeRepository.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeBasicRequestDto.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeUpdateRequestDto.java
  src/main/java/org/deco/gachicoding/dto/response/StatusEnum.java
  src/main/java/org/deco/gachicoding/service/NoticeService.java
Labels: 개발

#44 [Fix] 공지사항 작성 시 태그 오류 수정
  src/main/java/org/deco/gachicoding/controller/RestNoticeController.java
  src/main/java/org/deco/gachicoding/domain/notice/Notice.java
  src/main/java/org/deco/gachicoding/domain/user/User.java
  src/main/java/org/deco/gachicoding/dto/FileResponse.java
  src/main/java/org/deco/gachicoding/dto/RequestDto.java
  src/main/java/org/deco/gachicoding/dto/TagResponse.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeBasicRequestDto.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeSaveRequestDto.java
  src/main/java/org/deco/gachicoding/dto/notice/NoticeUpdateRequestDto.java
  src/main/java/org/deco/gachicoding/dto/tag/TagResponseDto.java
  src/main/java/org/deco/gachicoding/service/NoticeService.java
Labels: 버그, 수정

#55 #54 Refactor(Notice) : 공지사항 작성 리팩토링
  src/main/java/org/deco/gachicoding/post/notice/application/NoticeService.java
  src/main/java/org/deco/gachicoding/post/notice/domain/Notice.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/contents/NoticeContents.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/contents/NoticeTitle.java
  src/main/java/org/deco/gachicoding/post/notice/dto/NoticeDtoAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/dto/request/NoticeSaveRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/dto/request/NoticeUpdatePostRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/dto/response/NoticeResponseDto.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/RestNoticeController.java
  src/test/java/org/deco/gachicoding/unit/post/notice/domain/NoticeRepositoryTest.java
Labels: 개발, 수정

#61 #56 Refactor(Notice) : 공지사항 목록 리팩토링
  src/main/java/org/deco/gachicoding/post/notice/application/NoticeService.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/NoticeDtoAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/request/NoticeBasicRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/request/NoticeSaveRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/request/NoticeUpdateRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/response/NoticeResponseDto.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/response/NoticeUpdateResponseDto.java
  src/main/java/org/deco/gachicoding/post/notice/domain/Notice.java
  src/main/java/org/deco/gachicoding/post/notice/domain/repository/NoticeRepository.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/RestNoticeController.java
Labels: 수정

#71 [Refactor] 공지사항 API 날짜 데이터 리팩토링
  sql/DDL.sql
  src/main/java/org/deco/gachicoding/GachicodingApplication.java
  src/main/java/org/deco/gachicoding/common/BaseTimeEntity.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/NoticeDtoAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/response/NoticeResponseDto.java
  src/main/java/org/deco/gachicoding/post/notice/domain/Notice.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/NoticeAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/response/NoticeResponse.java
Labels: 개발

#74 #67 게시판 API 도메인 레이어 리팩토링
  sql/DDL.sql
  src/main/java/org/deco/gachicoding/post/board/application/BoardService.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardSaveRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardUpdateRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/response/BoardPostResponseDto.java
  src/main/java/org/deco/gachicoding/post/board/domain/Board.java
  src/main/java/org/deco/gachicoding/post/board/domain/repository/BoardRepository.java
  src/main/java/org/deco/gachicoding/post/board/domain/vo/BoardContents.java
  src/main/java/org/deco/gachicoding/post/board/domain/vo/BoardTitle.java
  src/main/java/org/deco/gachicoding/post/board/presentation/RestBoardController.java
  src/main/java/org/deco/gachicoding/post/notice/domain/Notice.java
  src/main/java/org/deco/gachicoding/post/notice/domain/repository/NoticeRepository.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/NoticeContents.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/NoticeTitle.java
Labels: 개발, 수정

#78 Refactor/spring security auth
  sql/DDL.sql
  src/main/java/org/deco/gachicoding/config/SecurityConfig.java
  src/main/java/org/deco/gachicoding/config/WebConfig.java
  src/main/java/org/deco/gachicoding/config/security/RestAuthenticationProvider.java
  src/main/java/org/deco/gachicoding/config/security/RestAuthenticationToken.java
  src/main/java/org/deco/gachicoding/config/security/RestLoginAuthenticationEntryPoint.java
  src/main/java/org/deco/gachicoding/config/security/RestLoginProcessingFilter.java
  src/main/java/org/deco/gachicoding/config/security/handler/RestAccessDeniedHandler.java
  src/main/java/org/deco/gachicoding/config/security/handler/RestAuthenticationFailureHandler.java
  src/main/java/org/deco/gachicoding/config/security/handler/RestAuthenticationSuccessHandler.java
  src/main/java/org/deco/gachicoding/user/application/UserDetailsServiceImpl.java
  src/main/java/org/deco/gachicoding/user/domain/User.java
  src/main/java/org/deco/gachicoding/user/dto/request/UserSaveRequestDto.java
  src/main/java/org/deco/gachicoding/user/presentation/RestLoginController.java
  src/main/java/org/deco/gachicoding/user/presentation/RestUserController.java
  src/test/java/org/deco/gachicoding/unit/user/application/UserDetailsServiceImplTest.java
  src/test/java/org/deco/gachicoding/unit/user/application/UserDetailsServiceImplTest2.java
Labels: 개발, 수정

#80 Hotfix/ compile error fix
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardBasicRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardDetailRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardListRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardSaveRequestDto.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/request/NoticeSaveRequestDto.java
Labels: 버그, 개발, 핫픽스

#82 Feat(RestLoginProcessingFilter) : 로그인 로직 완료
  src/main/java/org/deco/gachicoding/config/security/RestAuthenticationProvider.java
  src/main/java/org/deco/gachicoding/config/security/RestLoginProcessingFilter.java
  src/main/java/org/deco/gachicoding/config/security/handler/RestAuthenticationFailureHandler.java
  src/main/java/org/deco/gachicoding/config/security/handler/RestAuthenticationSuccessHandler.java
Labels: 개발, 수정

#93 Update(Notice, Board) : 프론트와 협업을 위한 부분적 롤백
  src/main/java/org/deco/gachicoding/exception/StatusEnum.java
  src/main/java/org/deco/gachicoding/post/board/application/dto/request/BoardSaveRequestDto.java
  src/main/java/org/deco/gachicoding/post/board/presentation/RestBoardController.java
  src/main/java/org/deco/gachicoding/post/board/presentation/dto/BoardAssembler.java
  src/main/java/org/deco/gachicoding/post/board/presentation/dto/request/BoardSaveRequest.java
  src/main/java/org/deco/gachicoding/post/board/presentation/dto/request/BoardUpdateRequest.java
  src/main/java/org/deco/gachicoding/post/board/presentation/dto/response/BoardResponse.java
  src/main/java/org/deco/gachicoding/post/notice/application/NoticeService.java
  src/main/java/org/deco/gachicoding/post/notice/application/dto/NoticeDtoAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/NoticeContents.java
  src/main/java/org/deco/gachicoding/post/notice/domain/vo/NoticeTitle.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/RestNoticeController.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/NoticeAssembler.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/request/NoticeSaveRequest.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/request/NoticeUpdateRequest.java
  src/main/java/org/deco/gachicoding/post/notice/presentation/dto/response/NoticeResponse.java
  src/test/java/org/deco/gachicoding/common/factory/post/notice/MockNotice.java
  src/test/java/org/deco/gachicoding/common/factory/post/notice/NoticeFactory.java
  src/test/java/org/deco/gachicoding/unit/post/notice/application/NoticeServiceTest.java
  src/test/java/org/deco/gachicoding/unit/post/notice/domain/NoticeTest.java
Labels: 수정
